relion/convert/convert.py, relion/viewers.py
Reviewed together with https://github.com/I2PC/scipion/pull/1836
=> Jmrt em refactor

relion/convert/convert.py, relion/protocols/__init__.py, relion/protocols/protocol_extract_particles_movies.py, relion/tests/test_protocols_relion.py
=> add missing protocol: extract movie ptcls

relion/protocols/protocol_base.py
read beamtilt and randomsubset from input setOfParticles  and save then in star file
=> fix conversion from sqlite to star

relion/__init__.py, relion/convert/convert.py, relion/protocols/protocol_base.py, relion/protocols/protocol_create_mask3d.py
Few small fixes addressed here:
* Scale provided masks when different size compared to particles
* Allow to pass different MPI variables for Relion
* Added support for threads in Relion mask create
=> Jmrt relion3 fixes

relion/protocols/protocol_base.py
=> add missing option

relion/convert/metadata.py, relion/protocols.conf, relion/protocols/protocol_bayesian_polishing.py, relion/protocols/protocol_export_particles.py, relion/protocols/protocol_motioncor.py, relion/protocols/protocol_multibody.py, relion/tests/test_protocols_relion.py, relion/tests/test_protocols_relion3.py, relion/viewers/viewers.py
Here we will be adding more commits to fix small issues before they go to devel.
=> Protocol fixes

CHANGES.txt, relion/protocols/protocol_refine3d.py, relion/tests/test_workflow_relion.py, relion/viewers/viewers.py, setup.py
=> release 1.0.6

relion/protocols/protocol_bayesian_polishing.py
=> Use SetMdIterator to ignore particles from missing movies

README.rst, relion/constants.py, relion/convert/convert_deprecated.py, relion/convert/metadata.py, relion/protocols/protocol_autopick.py, relion/protocols/protocol_base.py, relion/protocols/protocol_create_mask3d.py, relion/protocols/protocol_export_ctf.py, relion/protocols/protocol_extract_particles.py, relion/protocols/protocol_localres.py, relion/protocols/protocol_subtract.py, relion/tests/test_convert_relion.py, relion/tests/test_protocols_relion.py, relion/viewers/viewers.py, relion/wizards.py, setup.py
Todo: check TestConvertAnglesBase with relion 3.0
=> some fixes

relion/__init__.py, relion/protocols/protocol_assign_optic_groups.py, relion/protocols/protocol_motioncor.py, relion/tests/test_protocols_relion3.py, relion/viewers/viewers.py
* Depends on Acquistion changes here: https://github.com/scipion-em/scipion-em/pull/35
* Power spectra is asociated with outputMicrographs
=> Motioncor round 1

relion/convert/__init__.py, relion/convert/convert31.py, relion/convert/convert_base.py, relion/convert/convert_deprecated.py, relion/convert/convert_utils.py, relion/protocols/protocol_base.py, relion/protocols/protocol_classify3d.py, relion/protocols/protocol_export_particles.py, relion/protocols/protocol_initialmodel.py, relion/protocols/protocol_refine3d.py, relion/tests/test_protocols_relion.py
Now the basic workflow in Relion can be executed (maybe not everything working as it should be):
* 2d classification
* Subset good particles
* Relion initial model
* 3D classification
* Subset
* Scipion - extract coordinates
* Relion extract particles full size
* 3D autorefine
* Create 3D mask
* Postprocess
=> More on writing set of particles and binary images

relion/constants.py, relion/convert/__init__.py, relion/convert/convert30.py, relion/convert/convert31.py, relion/convert/convert_base.py, relion/protocols/__init__.py, relion/protocols/_legacy/protocol30_ctf_refinement.py, relion/protocols/protocol_base.py, relion/protocols/protocol_ctf_refinement.py, relion/protocols/protocol_refine3d.py
Changes:
* Added Reader class to parse Star file outputs
* Fixed continue parameters for Relion base protocol
* Added first running version of CTF-refinement (issues #132 )
=> Convert ctfrefine

relion/__init__.py
This tgz in our servers (provided by @azazellochg ) until relion3.1 provide a url to download.
=> point to i2pc server

relion/convert/convert31.py
_postprocessImageRow was added but never executed for 3.1
Or I couldn't find it in the code...
=> add postprocessRow

relion/convert/__init__.py, relion/convert/convert30.py, relion/convert/convert31.py, relion/convert/convert_base.py, relion/convert/convert_deprecated.py, relion/convert/convert_utils.py, relion/protocols/_legacy/protocol30_bayesian_polishing.py, relion/protocols/_legacy/protocol30_ctf_refinement.py, relion/protocols/protocol_base.py, relion/protocols/protocol_bayesian_polishing.py, relion/protocols/protocol_ctf_refinement.py, relion/protocols/protocol_expand_symmetry.py, relion/protocols/protocol_export_particles.py, relion/protocols/protocol_reconstruct.py, relion/protocols/protocol_sort.py, relion/protocols/protocol_subtract.py, relion/tests/test_convert_relion.py, relion/tests/test_protocols_relion.py
=> Fix convert

relion/protocols/__init__.py, relion/protocols/protocol_autopick.py, relion/protocols/protocol_compress_estimate_gain.py, relion/protocols/protocol_compress_movies.py
Added two protocols related to compression (both using relion_convert_to_tif):
* relion - compress movie
* relion - compress estimate gain
I haven't created any test since it will required original movies and can be quite heavy, but I'm open to suggestions.
=> First version of compress and estimate gain

relion/protocols/protocol_ctf_refinement.py, relion/viewers/viewer_ctfrefine.py
close #194 
@delarosatrevin is there a way to display several mrc files in one window and color them like in relion pdf logfile?
=> fix ctf refine viewer

relion/convert/__init__.py, relion/convert/convert30.py, setup.py
After this alignmentToRow and back works for 3.0
=> fix alignment conversions for 30

relion/viewers/viewer_locres.py, relion/wizards.py
LocalResoluton viewer_locres.py adapted to use the wizard.
This adds the colorScale wizard to the viewer.
=> ColorScaleWizard added

relion/__init__.py, relion/convert/convert31.py
Reported by Moustafa, Ibrahim M.
=> hotfix for missing ctf attrs

relion/protocols/protocol_subtract.py
overwriting self.inputParticles is detected by scipion and to allowed.
=> This is avoid error at persisting time

CHANGES.txt, relion/__init__.py, relion/protocols/protocol_base.py
=> quick fixes suggested by @rmarabini

CHANGES.txt, relion/__init__.py, relion/protocols/protocol_assign_optic_groups.py
=> abs paths are not allowed

CHANGES.txt, relion/__init__.py, relion/protocols/protocol_base.py
Hot fix for the issue reported by Serban Ilca
=> fix priors param conditions

relion/protocols/protocol_base.py, relion/protocols/protocol_bayesian_polishing.py, relion/protocols/protocol_ctf_refinement.py, relion/protocols/protocol_motioncor.py, relion/protocols/protocol_multibody.py, relion/protocols/protocol_postprocess.py, relion/protocols/protocol_reconstruct.py, relion/protocols/protocol_subtract.py
* Allow to use Environ.setPrepend (depend on https://github.com/scipion-em/scipion-pyworkflow/pull/238) to set different prepend commands (e.g when optimized CPU module is available)
=> Use prepend and refactor

README.rst, relion/__init__.py, relion/constants.py
Changed from tgz to git. Added some dependencies checks
=> update install routine

CHANGES.txt, relion/__init__.py, relion/protocols/protocol_autopick_ref.py
When picking using a 3D reference
=> fix validation

relion/convert/convert31.py, relion/convert/convert_base.py, relion/protocols/__init__.py, relion/protocols/protocol_import_coords.py, relion/tests/test_protocols_relion.py
=> add import coords protocol

relion/convert/__init__.py, relion/convert/dataimport.py, relion/protocols/protocol_base.py, relion/protocols/protocol_ctf_refinement.py, relion/viewers/viewer_base.py, relion/viewers/viewer_ctfrefine.py, relion/viewers/viewer_multibody.py, relion/viewers/viewer_postprocess.py
close #340
I've checked all affected viewers and both showj and chimera displays okay. The only place we cannot get rid of it is where we set representative volume names after 3d cls. 
@delarosatrevin could you review this asap if possible?
=> remove :mrc if possible

CHANGES.txt, README.rst, relion/__init__.py, relion/constants.py, relion/protocols/protocol_select_classes.py
Removed RELION_PYTHON, replaced by conda env variable RELION_ENV_ACTIVATION
=> add conda env for class 2d ranker

relion/__init__.py, relion/protocols/protocol_base.py
=> Hotfix gpu funcs

CHANGES.txt, relion/__init__.py, relion/protocols/protocol_multibody.py, relion/protocols/protocol_postprocess.py
=> fix typo in half2 filename

CHANGES.txt, relion/__init__.py, relion/protocols/protocol_select_classes.py, relion/viewers/viewer_base.py
* Generated outputParticles
* outputClasses now have rlnEstimatedResolution and rlnrlnPredictedClassScore attributes
* Improved summary using sumaryVar and handling when no output
* Added viewer for RelionSelect2DClasses
=> Updated 2d class ranker protocol

CHANGES.txt, relion/__init__.py, relion/protocols/protocol_classify3d.py
=> remove direct pointer

CHANGES.txt, relion/__init__.py, relion/protocols/protocol_reconstruct.py
=> add ewald params to reconstruct

CHANGES.txt, relion/__init__.py, relion/viewers/viewer_base.py
Closes https://github.com/scipion-em/scipion-em/issues/485
=> fix FSC viewer: Do not show empty figure when closing.
